export const data = [
  { number: "01", name: "Alex Smith", team: "Top Club", position: "Guard" },
  { number: "02", name: "Ben Johnson", team: "Top Club", position: "Forward" },
  { number: "03", name: "Kevin Harrell", team: "Top Club", position: "Guard" },
  { number: "04", name: "Chris Lee", team: "Top Club", position: "Center" },
  {
    number: "05",
    name: "James Fletcher",
    team: "Top Club",
    position: "Center",
  },
  { number: "06", name: "Michael Brown", team: "Top Club", position: "Guard" },
  { number: "07", name: "David Wilson", team: "Top Club", position: "Forward" },
  { number: "08", name: "Andrew Moore", team: "Top Club", position: "Guard" },
  {
    number: "09",
    name: "Matthew Taylor",
    team: "Top Club",
    position: "Forward",
  },
  {
    number: "10",
    name: "Joseph Anderson",
    team: "Top Club",
    position: "Center",
  },
  {
    number: "11",
    name: "Robert Thomas",
    team: "Top Club",
    position: "Forward",
  },
  { number: "12", name: "Daniel Jackson", team: "Top Club", position: "Guard" },
  {
    number: "13",
    name: "Paul White",
    team: "Top Club",
    position: "Forward-Guard",
  },
  {
    number: "14",
    name: "Jeff Montes",
    team: "Top Club",
    position: "Forward-Guard",
  },
  { number: "15", name: "Mark Harris", team: "Top Club", position: "Center" },
  { number: "16", name: "Steven Martin", team: "Top Club", position: "Guard" },
  {
    number: "17",
    name: "Kenneth Thompson",
    team: "Top Club",
    position: "Forward",
  },
  {
    number: "18",
    name: "Joshua Martinez",
    team: "Top Club",
    position: "Guard",
  },
  {
    number: "19",
    name: "Charles Robinson",
    team: "Top Club",
    position: "Forward",
  },
  { number: "20", name: "Jason Clark", team: "Top Club", position: "Center" },
];
